app/__init__.py
from flask import Flask

from config import Config

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app = create_app()  # This line ensures that the app object is created when the module is imported

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app.main import bp
from flask import render_template
from app.form import Form
import pickle

with open('pkl/model.pkl', 'rb') as f:
    model = pickle.load(f)

with open('pkl/scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

@bp.route('/', methods=['POST', 'GET'])
def info():
    form = Form()
    result = ""
    if form.validate_on_submit():
        location_choices = {
            choice[0]: False if choice[0] not in form.location.data else True for choice in form.location.choices
        }

        input_data = [
            form.age.data,
            int(form.gender.data),
            form.bmi.data,
            form.children.data,
            int(form.smoking.data),
            location_choices.get("northeast"),
            location_choices.get("northwest"),
            location_choices.get("southeast"),
            location_choices.get("southwest")
        ]

        # Scale the input using the loaded scaler
        scaled_input = scaler.transform([input_data])

        result = round(model.predict(scaled_input)[0], 2)

    return render_template("index.html", form=form, result=result)

app/templates/index.html
{% from "render_field.html" import render_field %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<link rel="icon" type="image/x-icon" href="{{url_for('static',filename='images/site-logo.png')}}">
<link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
  <script>
    $(document).ready(function(){
      $(this).scrollTop(0);
    });
  </script>
  <title>Medical insurance price predictor</title>
</head>
<body>
  <section   style="min-height: 100vh; background-image: linear-gradient(to right, rgb(134, 239, 172), rgb(59, 130, 246), rgb(147, 51, 234));">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-left h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card rounded-3" style="background-color: rgb(252, 252, 252);">
            <div class="card-body p-4">
        <form method="POST" action="{{url_for('main.info')}}" novalidate>

            <center>
              <h4 class="head">Medical insurance price predictor</h4>
              {% if result %}
              <div class="result">
                <p>Predicted insurance price : {{result}}💲</p>
              </div>
              {% endif %}
          {{ form.csrf_token }}
          <div class="form-outline mb-4">
            {{ render_field(form.age) }}
          </div>
          <div class="form-outline mb-4">
            {{ render_field(form.bmi) }}
          </div>
          <div class="form-outline mb-4">
            {{ render_field(form.children) }}
          </div>
          <div class="form-outline mb-4">
            {{form.location( class="form-select")}}
            {{form.location.label}}
          </div>
          <hr>
          <div class="form-outline mb-4">
            {{ form.smoking }}
            {{form.smoking.label}}
          </div>
          <hr>
          <div class="form-outline mb-4">
                <div style="border: 1px solid rgb(59, 130, 246);width: 40%;border-radius: 8px;">
                  {% for choice in form.gender %}
                  {{ choice(class="form-check-input") }}
                  {{ choice.label(class="form-check-label") }}<br>
                  {% endfor %}
                </div>
            {{ form.gender.label }}

            </div>
            {% for error in form.gender.errors %}
            <div style="background-color: rgb(255, 100, 44);color: rgb(63, 63, 63);">
              {{ error }}
            </div>
            {% endfor %}
        </div>
              <center>
          <div class="form-outline mb-4">
            {{ form.submit(class="btn btn-primary btn-lg btn-block") }}
          </div>

              </center>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

app/templates/render_field.html
{% macro render_field(field) %}
    {% if field.errors %}
        <dd>{{ field(class="form-control", style="background-color: rgb(255, 100, 44);", **kwargs) | safe }}
            <ul>
                {% for error in field.errors %}
                    <li class="list-group-item list-group-item-danger"> {{error}} </li>
                {% endfor %}
                <dt>{{ field.label }}

            </ul>
        </dd>
    {% else %}
        <dd>{{ field(class="form-control") | safe }} </dd>
        <dt>{{ field.label }}
        <br>
    {% endif %}
{% endmacro %}